#!/bin/bash
# Take daily back ups of my SQL docker images - with structure and data
D="$(date)"
echo "MySQL database back up begins at: $D"


#take back up of mysql daily once
docker exec  $(docker ps -f name=tmysql -q) sh -c 'exec mysqldump --all-databases -uroot -pTestdata@2k18' > /home/svcdocker/msqlbackup/all-databases.$(date +"%m%d%Y_%H%M%S").sql

if [ "$?" -eq 0 ]
then
    echo "`date` : Mysql database backup completed successfully" >> /home/svcdocker/msqlbackup/log
else
    echo "`date` : Mysql Database backup  failed" >> /home/svcdocker/msqlbackup/log
fi

#Cron this job to run daily at 22.00 PM EST
# * 22 * * *

mysqlbckup_file=$(ls -t  all-databases.* | head -n 1)

curl -v -uTQSuser:tqs!re@o \
   --upload-file all-databases.07292018_220001.sql \
   http://10.32.6.113:8081/nexus/content/repositories/TQS/1.0.0/all-databases.07292018_220001.sql
